#---------------------------
# 页头
# Header
#---------------------------

# 导航栏的相关配置
# Navigation bar
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title:


#---------------------------
# 首页
# Home Page
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  banner_img: /img/background.png

  slogan:
    # 为空则按 hexo config.subtitle 显示
    # If empty, text based on `subtitle` in hexo config
    text:


#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: /img/background.png

  comments:
    enable: true
    # 指定的插件，需要同时设置对应插件的必要参数
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis | giscus | discuss
    type: giscus


#---------------------------
# 评论插件
# Comment plugins
#
# 开启评论需要先设置上方 `post: comments: enable: true`，然后根据 `type` 设置下方对应的评论插件参数
# Enable comments need to be set `post: comments: enable: true`, then set the corresponding comment plugin parameters below according to `type`
#---------------------------

# Giscus
# 基于 GitHub Discussions，类似于 Utterances
# Based on GitHub Discussions, similar to Utterances
# See: https://giscus.app/
giscus:
  repo: FredBill1/FredBill1.github.io
  repo-id: R_kgDOKsKEdA
  category: General
  category-id: DIC_kwDOKsKEdM4Ca4I6
  theme: preferred_color_scheme
  mapping: pathname
  strict: 1
  reactions-enabled: 1
  emit-metadata: 0
  input-position: bottom
  lang: zh-CN
  loading: lazy

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/background.png


#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  banner_img: /img/background.png


#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/background.png


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: https://avatars.githubusercontent.com/FredBill1
  name: FredBill
  intro: 😋
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/FredBill1", tip: "GitHub" }


#---------------------------
# 自定义页
# Custom Page
#
# 通过 hexo new page 命令创建的页面
# Custom Page through `hexo new page`
#---------------------------
page:
  banner_img: /img/background.png


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: /img/background.png


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  enable: true
  banner_img: /img/background.png