# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: FredBill's Blog
description: ''
keywords:
author: FredBill
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.fredbill.eu.org/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''


# Content blocks
## Docs: https://github.com/Sukwants/hexo-content-blocks
content_blocks:
  enable: true
  open_button: '<svg class="content-i" viewBox="0 0 100 100" width=0.7rem height=0.7rem><polygon points="50 0, 100 85, 0 85"/></svg>'
  types:
    code: '#448aff ||| <i class="content-i iconfont icon-code"></i>'
    note: '#448aff ||| <i class="content-i fa fa-pen"></i>'
    abstract: '#00b0ff ||| <i class="content-i fa fa-clipboard-list"></i>'
    info: '#00b8d4 ||| <i class="content-i fa fa-circle-info"></i>'
    tip: '#00bfa5 ||| <i class="content-i fa fa-fire"></i>'
    success: '#00c853 ||| <i class="content-i fa fa-check"></i>'
    question: '#64dd17 ||| <i class="content-i fa fa-circle-question"></i>'
    warning: '#ff9100 ||| <i class="content-i fa fa-triangle-exclamation"></i>'
    failure: '#ff5252 ||| <i class="content-i fa fa-xmark"></i>'
    danger: '#ff1744 ||| <i class="content-i fa fa-bolt"></i>'
    bug: '#f50057 ||| <i class="content-i fa fa-bug"></i>'
    example: '#7c4dff ||| <i class="content-i fa fa-vial"></i>'
    quote: '#9e9e9e ||| <i class="content-i fa fa-quote-right"></i>'